# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 518)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.new_task_TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.new_task_TextEdit.setGeometry(QtCore.QRect(20, 10, 321, 31))
        self.new_task_TextEdit.setObjectName("new_task_TextEdit")
        self.groups_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.groups_comboBox.setGeometry(QtCore.QRect(20, 190, 151, 25))
        self.groups_comboBox.setAcceptDrops(True)
        self.groups_comboBox.setEditable(True)
        self.groups_comboBox.setIconSize(QtCore.QSize(12, 12))
        self.groups_comboBox.setObjectName("groups_comboBox")
        self.groups_comboBox.addItem("")
        self.groups_comboBox.addItem("")
        self.groups_comboBox.addItem("")
        self.groups_comboBox.addItem("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Addition.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groups_comboBox.addItem(icon, "")
        self.end_date_label = QtWidgets.QLabel(self.centralwidget)
        self.end_date_label.setGeometry(QtCore.QRect(190, 60, 111, 20))
        self.end_date_label.setObjectName("end_date_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 520, 341, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 341, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(340, 0, 21, 541))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tasks_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tasks_tabWidget.setEnabled(True)
        self.tasks_tabWidget.setGeometry(QtCore.QRect(370, 10, 391, 531))
        self.tasks_tabWidget.setAutoFillBackground(True)
        self.tasks_tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tasks_tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tasks_tabWidget.setDocumentMode(False)
        self.tasks_tabWidget.setTabsClosable(True)
        self.tasks_tabWidget.setMovable(True)
        self.tasks_tabWidget.setTabBarAutoHide(False)
        self.tasks_tabWidget.setObjectName("tasks_tabWidget")
        self.All_tab = QtWidgets.QWidget()
        self.All_tab.setObjectName("All_tab")
        self.allTasks_listWidget = QtWidgets.QListWidget(self.All_tab)
        self.allTasks_listWidget.setGeometry(QtCore.QRect(-20, 0, 401, 421))
        self.allTasks_listWidget.setGridSize(QtCore.QSize(0, 30))
        self.allTasks_listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.allTasks_listWidget.setModelColumn(0)
        self.allTasks_listWidget.setUniformItemSizes(False)
        self.allTasks_listWidget.setWordWrap(False)
        self.allTasks_listWidget.setObjectName("allTasks_listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.allTasks_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.allTasks_listWidget.addItem(item)
        self.tasks_tabWidget.addTab(self.All_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tasks_tabWidget.addTab(self.tab_2, "")
        self.edit_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.edit_PushButton.setGeometry(QtCore.QRect(20, 260, 91, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit_PushButton.setFont(font)
        self.edit_PushButton.setObjectName("edit_PushButton")
        self.delete_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_PushButton.setGeometry(QtCore.QRect(130, 260, 91, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_PushButton.setFont(font)
        self.delete_PushButton.setObjectName("delete_PushButton")
        self.selectAll_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectAll_PushButton.setGeometry(QtCore.QRect(250, 260, 91, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectAll_PushButton.setFont(font)
        self.selectAll_PushButton.setObjectName("selectAll_PushButton")
        self.save_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_PushButton.setGeometry(QtCore.QRect(190, 190, 151, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_PushButton.setFont(font)
        self.save_PushButton.setAutoFillBackground(False)
        self.save_PushButton.setObjectName("save_PushButton")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 300, 341, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.archive_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.archive_PushButton.setGeometry(QtCore.QRect(20, 330, 141, 25))
        self.archive_PushButton.setObjectName("archive_PushButton")
        self.mark_as_completed_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mark_as_completed_PushButton.setGeometry(QtCore.QRect(190, 330, 151, 25))
        self.mark_as_completed_PushButton.setObjectName("mark_as_completed_PushButton")
        self.create_new_group_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.create_new_group_PushButton.setGeometry(QtCore.QRect(20, 370, 321, 25))
        self.create_new_group_PushButton.setObjectName("create_new_group_PushButton")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 410, 351, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.groups_Label = QtWidgets.QLabel(self.centralwidget)
        self.groups_Label.setGeometry(QtCore.QRect(20, 420, 67, 17))
        self.groups_Label.setObjectName("groups_Label")
        self.start_date_label = QtWidgets.QLabel(self.centralwidget)
        self.start_date_label.setGeometry(QtCore.QRect(20, 60, 121, 17))
        self.start_date_label.setObjectName("start_date_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 170, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(46, 52, 54);")
        self.label.setObjectName("label")
        self.start_dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.start_dateEdit.setGeometry(QtCore.QRect(20, 90, 151, 26))
        self.start_dateEdit.setProperty("showGroupSeparator", False)
        self.start_dateEdit.setCalendarPopup(True)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.end_dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.end_dateEdit.setGeometry(QtCore.QRect(190, 90, 151, 26))
        self.end_dateEdit.setCalendarPopup(True)
        self.end_dateEdit.setObjectName("end_dateEdit")
        self.start_timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.start_timeEdit.setGeometry(QtCore.QRect(20, 130, 118, 26))
        self.start_timeEdit.setObjectName("start_timeEdit")
        self.end_timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.end_timeEdit.setGeometry(QtCore.QRect(190, 130, 118, 26))
        self.end_timeEdit.setObjectName("end_timeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tasks_tabWidget.setCurrentIndex(0)
        self.allTasks_listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TODO...your loyal task manager"))
        self.new_task_TextEdit.setPlaceholderText(_translate("MainWindow", "Type your new task here"))
        self.groups_comboBox.setItemText(0, _translate("MainWindow", "Personal"))
        self.groups_comboBox.setItemText(1, _translate("MainWindow", "Work"))
        self.groups_comboBox.setItemText(2, _translate("MainWindow", "Friends"))
        self.groups_comboBox.setItemText(3, _translate("MainWindow", "Family"))
        self.groups_comboBox.setItemText(4, _translate("MainWindow", "New Group"))
        self.end_date_label.setText(_translate("MainWindow", "End Date/Time"))
        __sortingEnabled = self.allTasks_listWidget.isSortingEnabled()
        self.allTasks_listWidget.setSortingEnabled(False)
        item = self.allTasks_listWidget.item(0)
        item.setText(_translate("MainWindow", "hello "))
        item = self.allTasks_listWidget.item(1)
        item.setText(_translate("MainWindow", "how may i help you"))
        self.allTasks_listWidget.setSortingEnabled(__sortingEnabled)
        self.tasks_tabWidget.setTabText(self.tasks_tabWidget.indexOf(self.All_tab), _translate("MainWindow", "All"))
        self.tasks_tabWidget.setTabText(self.tasks_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.edit_PushButton.setText(_translate("MainWindow", "Edit"))
        self.delete_PushButton.setText(_translate("MainWindow", "Delete"))
        self.selectAll_PushButton.setText(_translate("MainWindow", "Select all"))
        self.save_PushButton.setText(_translate("MainWindow", "Save"))
        self.archive_PushButton.setText(_translate("MainWindow", "Archive"))
        self.mark_as_completed_PushButton.setText(_translate("MainWindow", "Mark as completed"))
        self.create_new_group_PushButton.setText(_translate("MainWindow", "Create new group"))
        self.groups_Label.setText(_translate("MainWindow", "Groups"))
        self.start_date_label.setText(_translate("MainWindow", "Start Date/Time"))
        self.label.setText(_translate("MainWindow", "Group as"))
        self.start_dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.end_dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))

